#!/usr/bin/python3
import sys
import store
import rpmmd
import newmd

cmd = sys.argv[1]

if cmd == 'convert':
    src = sys.argv[2]
    dst = sys.argv[3]
    rpmmd.LibrepoPool(src, dst)
    sys.exit()

slave = rpmmd.Pool('/tmp/rhs', rpmmd.spec)
st = store.Store(slave)

if cmd == 'fetch':
    arg = sys.argv[2]
    if arg == '--compat':
        url = sys.argv[3]
        with rpmmd.LibrepoPool(url, None) as master:
            st.fetch(master)
    else:
        url = sys.argv[2]
        with newmd.HTTPPool(url, rpmmd.spec) as master:
            st.fetch(master)
elif cmd == 'checkout':
    ref = sys.argv[2]
    st.checkout(ref)
