#!/usr/bin/python3
import sys
import store
import rpmmd

cmd = sys.argv[1]

slave = rpmmd.SlavePool('/tmp/rhs', rpmmd.spec)
st = store.Store(slave)

if cmd == 'fetch':
    url = sys.argv[2]
    with rpmmd.MasterPool(url, None) as master:
        st.fetch(master)
elif cmd == 'checkout':
    ref = sys.argv[2]
    st.checkout(ref)
