#!/usr/bin/python3
import sys
import store
import rpmmd

cmd = sys.argv[1]

slave = rpmmd.Pool('/tmp/rhs', rpmmd.spec)
st = store.Store(slave)

if cmd == 'fetch':
    arg = sys.argv[2]
    if arg == '--compat':
        url = sys.argv[3]
        with rpmmd.LibrepoPool(url, None) as master:
            st.fetch(master)
    else:
        url = sys.argv[2]
        with store.HTTPPool(url, rpmmd.spec) as master:
            st.fetch(master)
elif cmd == 'checkout':
    ref = sys.argv[2]
    st.checkout(ref)
